language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - ZOOPLA_KEY=notusedintests
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --all
  - cargo test --all

# vim: sw=2:ts=2
