[package]
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
name = "zooplaapi"
version = "0.1.0"

[dependencies]
dotenv = "0.10.1"
reqwest = "0.8.4"

[dependencies.diesel]
features = ["postgres"]
version = "1.1.1"
